version: '3'
services:
  es:
    image: elasticsearch:7.8.1
    # volumes:
    #   - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: 'single-node'
      # xpack.security.enabled: 'true'
      # ELASTIC_PASSWORD: 'my_password'
    networks:
      - elastic
  kibana:
    image: kibana:7.8.1
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - elastic
  api:
    build: ./api
    container_name: api_c
    restart: unless-stopped
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
    # command: python manage.py runserver localhost:8000
    ports:
        - 8000:8000
    volumes:
      - ./api:/app
    depends_on:
      - es
    networks:
      - elastic

networks:
  elastic:
    driver: bridge