version: '3'
services:
  es:
    image: elasticsearch:7.8.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: 'single-node'
  
  kibana:
    image: kibana:7.8.1
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
  
  api:
    build: ./api
    container_name: api_c
    restart: unless-stopped
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
    ports:
        - 8000:8000
    volumes:
      - ./api:/app
    depends_on:
      - es